/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AtomDotxmlRouteImport } from './routes/atom[.]xml'
import { Route as FeedDotjsonRouteImport } from './routes/feed[.]json'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SiteDotwebmanifestRouteImport } from './routes/site[.]webmanifest'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatsDotjsRouteImport } from './routes/stats[.]js'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSplatRouteImport } from './routes/_public/$'
import { Route as PublicAuthRouteRouteImport } from './routes/_public/_auth/route'
import { Route as PublicUserRouteRouteImport } from './routes/_public/_user/route'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicEnginesRouteImport } from './routes/_public/engines'
import { Route as PublicNavigatorRouteImport } from './routes/_public/navigator'
import { Route as PublicPolicyRouteImport } from './routes/_public/policy'
import { Route as PublicPostsRouteImport } from './routes/_public/posts'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as PublicUndergroundRouteImport } from './routes/_public/underground'
import { Route as PublicUnsubscribeRouteImport } from './routes/_public/unsubscribe'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as AdminPostsRouteRouteImport } from './routes/admin/posts/route'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiAuthRouteImport } from './routes/api.auth'
import { Route as ApiSendRouteImport } from './routes/api.send'
import { Route as ImagesSplatRouteImport } from './routes/images.$'
import { Route as PublicAuthForgotPasswordRouteImport } from './routes/_public/_auth/forgot-password'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/_auth/register'
import { Route as PublicAuthResetLinkRouteImport } from './routes/_public/_auth/reset-link'
import { Route as PublicAuthVerifyEmailRouteImport } from './routes/_public/_auth/verify-email'
import { Route as PublicUserProfileRouteImport } from './routes/_public/_user/profile'
import { Route as PublicOrganizationIndexRouteImport } from './routes/_public/organization/index'
import { Route as PublicOrganizationSlugRouteImport } from './routes/_public/organization/$slug'
import { Route as PublicPostSlugRouteImport } from './routes/_public/post/$slug'
import { Route as AdminFriendLinksIndexRouteImport } from './routes/admin/friend-links/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminMutedUsersIndexRouteImport } from './routes/admin/muted-users/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminSettingsApiKeysRouteImport } from './routes/admin/settings/api-keys'
import { Route as AdminSettingsDataSourcesRouteImport } from './routes/admin/settings/data-sources'
import { Route as AdminSettingsMaintenanceRouteImport } from './routes/admin/settings/maintenance'
import { Route as AdminSettingsNotificationsRouteImport } from './routes/admin/settings/notifications'
import { Route as AdminSettingsSiteRouteImport } from './routes/admin/settings/site'
import { Route as AdminTagsIndexRouteImport } from './routes/admin/tags/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AdminPostsEditIdRouteRouteImport } from './routes/admin/posts/edit.$id/route'
import { Route as AdminPostsEditIdIndexRouteImport } from './routes/admin/posts/edit.$id/index'
import { Route as AdminPostsEditIdHistoryRouteImport } from './routes/admin/posts/edit.$id/history'
import { Route as AdminPostsEditIdHistoryRevisionIdRouteImport } from './routes/admin/posts/edit.$id/history_.$revisionId'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomDotxmlRoute = AtomDotxmlRouteImport.update({
  id: '/atom.xml',
  path: '/atom.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotjsonRoute = FeedDotjsonRouteImport.update({
  id: '/feed.json',
  path: '/feed.json',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteDotwebmanifestRoute = SiteDotwebmanifestRouteImport.update({
  id: '/site.webmanifest',
  path: '/site.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsDotjsRoute = StatsDotjsRouteImport.update({
  id: '/stats.js',
  path: '/stats.js',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSplatRoute = PublicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthRouteRoute = PublicAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicUserRouteRoute = PublicUserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEnginesRoute = PublicEnginesRouteImport.update({
  id: '/engines',
  path: '/engines',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicNavigatorRoute = PublicNavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPolicyRoute = PublicPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPostsRoute = PublicPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicUndergroundRoute = PublicUndergroundRouteImport.update({
  id: '/underground',
  path: '/underground',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicUnsubscribeRoute = PublicUnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsRouteRoute = AdminPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesSplatRoute = ImagesSplatRouteImport.update({
  id: '/images/$',
  path: '/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthForgotPasswordRoute =
  PublicAuthForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => PublicAuthRouteRoute,
  } as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicAuthResetLinkRoute = PublicAuthResetLinkRouteImport.update({
  id: '/reset-link',
  path: '/reset-link',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicAuthVerifyEmailRoute = PublicAuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicUserProfileRoute = PublicUserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PublicUserRouteRoute,
} as any)
const PublicOrganizationIndexRoute = PublicOrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicOrganizationSlugRoute = PublicOrganizationSlugRouteImport.update({
  id: '/organization/$slug',
  path: '/organization/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPostSlugRoute = PublicPostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminFriendLinksIndexRoute = AdminFriendLinksIndexRouteImport.update({
  id: '/friend-links/',
  path: '/friend-links/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMutedUsersIndexRoute = AdminMutedUsersIndexRouteImport.update({
  id: '/muted-users/',
  path: '/muted-users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsApiKeysRoute = AdminSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsDataSourcesRoute =
  AdminSettingsDataSourcesRouteImport.update({
    id: '/data-sources',
    path: '/data-sources',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsMaintenanceRoute =
  AdminSettingsMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsNotificationsRoute =
  AdminSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsSiteRoute = AdminSettingsSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminTagsIndexRoute = AdminTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiAuthRoute,
} as any)
const AdminPostsEditIdRouteRoute = AdminPostsEditIdRouteRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminPostsRouteRoute,
} as any)
const AdminPostsEditIdIndexRoute = AdminPostsEditIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsEditIdRouteRoute,
} as any)
const AdminPostsEditIdHistoryRoute = AdminPostsEditIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminPostsEditIdRouteRoute,
} as any)
const AdminPostsEditIdHistoryRevisionIdRoute =
  AdminPostsEditIdHistoryRevisionIdRouteImport.update({
    id: '/history_/$revisionId',
    path: '/history/$revisionId',
    getParentRoute: () => AdminPostsEditIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/atom.xml': typeof AtomDotxmlRoute
  '/feed.json': typeof FeedDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats.js': typeof StatsDotjsRoute
  '/admin/posts': typeof AdminPostsRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/$': typeof PublicSplatRoute
  '/about': typeof PublicAboutRoute
  '/engines': typeof PublicEnginesRoute
  '/navigator': typeof PublicNavigatorRoute
  '/policy': typeof PublicPolicyRoute
  '/posts': typeof PublicPostsRoute
  '/search': typeof PublicSearchRoute
  '/underground': typeof PublicUndergroundRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/send': typeof ApiSendRoute
  '/images/$': typeof ImagesSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/reset-link': typeof PublicAuthResetLinkRoute
  '/verify-email': typeof PublicAuthVerifyEmailRoute
  '/profile': typeof PublicUserProfileRoute
  '/organization/$slug': typeof PublicOrganizationSlugRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/admin/settings/api-keys': typeof AdminSettingsApiKeysRoute
  '/admin/settings/data-sources': typeof AdminSettingsDataSourcesRoute
  '/admin/settings/maintenance': typeof AdminSettingsMaintenanceRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/site': typeof AdminSettingsSiteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organization/': typeof PublicOrganizationIndexRoute
  '/admin/friend-links/': typeof AdminFriendLinksIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/muted-users/': typeof AdminMutedUsersIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRouteRouteWithChildren
  '/admin/posts/edit/$id/history': typeof AdminPostsEditIdHistoryRoute
  '/admin/posts/edit/$id/': typeof AdminPostsEditIdIndexRoute
  '/admin/posts/edit/$id/history/$revisionId': typeof AdminPostsEditIdHistoryRevisionIdRoute
}
export interface FileRoutesByTo {
  '/atom.xml': typeof AtomDotxmlRoute
  '/feed.json': typeof FeedDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats.js': typeof StatsDotjsRoute
  '/': typeof PublicIndexRoute
  '/$': typeof PublicSplatRoute
  '/about': typeof PublicAboutRoute
  '/engines': typeof PublicEnginesRoute
  '/navigator': typeof PublicNavigatorRoute
  '/policy': typeof PublicPolicyRoute
  '/posts': typeof PublicPostsRoute
  '/search': typeof PublicSearchRoute
  '/underground': typeof PublicUndergroundRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/send': typeof ApiSendRoute
  '/images/$': typeof ImagesSplatRoute
  '/admin': typeof AdminIndexRoute
  '/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/reset-link': typeof PublicAuthResetLinkRoute
  '/verify-email': typeof PublicAuthVerifyEmailRoute
  '/profile': typeof PublicUserProfileRoute
  '/organization/$slug': typeof PublicOrganizationSlugRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/admin/settings/api-keys': typeof AdminSettingsApiKeysRoute
  '/admin/settings/data-sources': typeof AdminSettingsDataSourcesRoute
  '/admin/settings/maintenance': typeof AdminSettingsMaintenanceRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/site': typeof AdminSettingsSiteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organization': typeof PublicOrganizationIndexRoute
  '/admin/friend-links': typeof AdminFriendLinksIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/muted-users': typeof AdminMutedUsersIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/tags': typeof AdminTagsIndexRoute
  '/admin/posts/edit/$id/history': typeof AdminPostsEditIdHistoryRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdIndexRoute
  '/admin/posts/edit/$id/history/$revisionId': typeof AdminPostsEditIdHistoryRevisionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/atom.xml': typeof AtomDotxmlRoute
  '/feed.json': typeof FeedDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats.js': typeof StatsDotjsRoute
  '/_public/_auth': typeof PublicAuthRouteRouteWithChildren
  '/_public/_user': typeof PublicUserRouteRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/_public/$': typeof PublicSplatRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/engines': typeof PublicEnginesRoute
  '/_public/navigator': typeof PublicNavigatorRoute
  '/_public/policy': typeof PublicPolicyRoute
  '/_public/posts': typeof PublicPostsRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/underground': typeof PublicUndergroundRoute
  '/_public/unsubscribe': typeof PublicUnsubscribeRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/send': typeof ApiSendRoute
  '/images/$': typeof ImagesSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/_auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_public/_auth/register': typeof PublicAuthRegisterRoute
  '/_public/_auth/reset-link': typeof PublicAuthResetLinkRoute
  '/_public/_auth/verify-email': typeof PublicAuthVerifyEmailRoute
  '/_public/_user/profile': typeof PublicUserProfileRoute
  '/_public/organization/$slug': typeof PublicOrganizationSlugRoute
  '/_public/post/$slug': typeof PublicPostSlugRoute
  '/admin/settings/api-keys': typeof AdminSettingsApiKeysRoute
  '/admin/settings/data-sources': typeof AdminSettingsDataSourcesRoute
  '/admin/settings/maintenance': typeof AdminSettingsMaintenanceRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/site': typeof AdminSettingsSiteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_public/organization/': typeof PublicOrganizationIndexRoute
  '/admin/friend-links/': typeof AdminFriendLinksIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/muted-users/': typeof AdminMutedUsersIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRouteRouteWithChildren
  '/admin/posts/edit/$id/history': typeof AdminPostsEditIdHistoryRoute
  '/admin/posts/edit/$id/': typeof AdminPostsEditIdIndexRoute
  '/admin/posts/edit/$id/history_/$revisionId': typeof AdminPostsEditIdHistoryRevisionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/atom.xml'
    | '/feed.json'
    | '/robots.txt'
    | '/rss.xml'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/stats.js'
    | '/admin/posts'
    | '/admin/settings'
    | '/$'
    | '/about'
    | '/engines'
    | '/navigator'
    | '/policy'
    | '/posts'
    | '/search'
    | '/underground'
    | '/unsubscribe'
    | '/admin/$'
    | '/api/$'
    | '/api/auth'
    | '/api/send'
    | '/images/$'
    | '/admin/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-link'
    | '/verify-email'
    | '/profile'
    | '/organization/$slug'
    | '/post/$slug'
    | '/admin/settings/api-keys'
    | '/admin/settings/data-sources'
    | '/admin/settings/maintenance'
    | '/admin/settings/notifications'
    | '/admin/settings/site'
    | '/api/auth/$'
    | '/organization/'
    | '/admin/friend-links/'
    | '/admin/media/'
    | '/admin/muted-users/'
    | '/admin/posts/'
    | '/admin/settings/'
    | '/admin/tags/'
    | '/admin/posts/edit/$id'
    | '/admin/posts/edit/$id/history'
    | '/admin/posts/edit/$id/'
    | '/admin/posts/edit/$id/history/$revisionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/atom.xml'
    | '/feed.json'
    | '/robots.txt'
    | '/rss.xml'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/stats.js'
    | '/'
    | '/$'
    | '/about'
    | '/engines'
    | '/navigator'
    | '/policy'
    | '/posts'
    | '/search'
    | '/underground'
    | '/unsubscribe'
    | '/admin/$'
    | '/api/$'
    | '/api/auth'
    | '/api/send'
    | '/images/$'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-link'
    | '/verify-email'
    | '/profile'
    | '/organization/$slug'
    | '/post/$slug'
    | '/admin/settings/api-keys'
    | '/admin/settings/data-sources'
    | '/admin/settings/maintenance'
    | '/admin/settings/notifications'
    | '/admin/settings/site'
    | '/api/auth/$'
    | '/organization'
    | '/admin/friend-links'
    | '/admin/media'
    | '/admin/muted-users'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/posts/edit/$id/history'
    | '/admin/posts/edit/$id'
    | '/admin/posts/edit/$id/history/$revisionId'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/atom.xml'
    | '/feed.json'
    | '/robots.txt'
    | '/rss.xml'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/stats.js'
    | '/_public/_auth'
    | '/_public/_user'
    | '/admin/posts'
    | '/admin/settings'
    | '/_public/$'
    | '/_public/about'
    | '/_public/engines'
    | '/_public/navigator'
    | '/_public/policy'
    | '/_public/posts'
    | '/_public/search'
    | '/_public/underground'
    | '/_public/unsubscribe'
    | '/admin/$'
    | '/api/$'
    | '/api/auth'
    | '/api/send'
    | '/images/$'
    | '/_public/'
    | '/admin/'
    | '/_public/_auth/forgot-password'
    | '/_public/_auth/login'
    | '/_public/_auth/register'
    | '/_public/_auth/reset-link'
    | '/_public/_auth/verify-email'
    | '/_public/_user/profile'
    | '/_public/organization/$slug'
    | '/_public/post/$slug'
    | '/admin/settings/api-keys'
    | '/admin/settings/data-sources'
    | '/admin/settings/maintenance'
    | '/admin/settings/notifications'
    | '/admin/settings/site'
    | '/api/auth/$'
    | '/_public/organization/'
    | '/admin/friend-links/'
    | '/admin/media/'
    | '/admin/muted-users/'
    | '/admin/posts/'
    | '/admin/settings/'
    | '/admin/tags/'
    | '/admin/posts/edit/$id'
    | '/admin/posts/edit/$id/history'
    | '/admin/posts/edit/$id/'
    | '/admin/posts/edit/$id/history_/$revisionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AtomDotxmlRoute: typeof AtomDotxmlRoute
  FeedDotjsonRoute: typeof FeedDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SiteDotwebmanifestRoute: typeof SiteDotwebmanifestRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsDotjsRoute: typeof StatsDotjsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthRoute: typeof ApiAuthRouteWithChildren
  ApiSendRoute: typeof ApiSendRoute
  ImagesSplatRoute: typeof ImagesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atom.xml': {
      id: '/atom.xml'
      path: '/atom.xml'
      fullPath: '/atom.xml'
      preLoaderRoute: typeof AtomDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.json': {
      id: '/feed.json'
      path: '/feed.json'
      fullPath: '/feed.json'
      preLoaderRoute: typeof FeedDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site.webmanifest': {
      id: '/site.webmanifest'
      path: '/site.webmanifest'
      fullPath: '/site.webmanifest'
      preLoaderRoute: typeof SiteDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats.js': {
      id: '/stats.js'
      path: '/stats.js'
      fullPath: '/stats.js'
      preLoaderRoute: typeof StatsDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/$': {
      id: '/_public/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PublicSplatRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicAuthRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_user': {
      id: '/_public/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicUserRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/engines': {
      id: '/_public/engines'
      path: '/engines'
      fullPath: '/engines'
      preLoaderRoute: typeof PublicEnginesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/navigator': {
      id: '/_public/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof PublicNavigatorRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/policy': {
      id: '/_public/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PublicPolicyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/posts': {
      id: '/_public/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PublicPostsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/underground': {
      id: '/_public/underground'
      path: '/underground'
      fullPath: '/underground'
      preLoaderRoute: typeof PublicUndergroundRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/unsubscribe': {
      id: '/_public/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof PublicUnsubscribeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$': {
      id: '/images/$'
      path: '/images/$'
      fullPath: '/images/$'
      preLoaderRoute: typeof ImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth/forgot-password': {
      id: '/_public/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicAuthForgotPasswordRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/register': {
      id: '/_public/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/reset-link': {
      id: '/_public/_auth/reset-link'
      path: '/reset-link'
      fullPath: '/reset-link'
      preLoaderRoute: typeof PublicAuthResetLinkRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/verify-email': {
      id: '/_public/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicAuthVerifyEmailRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_user/profile': {
      id: '/_public/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PublicUserProfileRouteImport
      parentRoute: typeof PublicUserRouteRoute
    }
    '/_public/organization/': {
      id: '/_public/organization/'
      path: '/organization'
      fullPath: '/organization/'
      preLoaderRoute: typeof PublicOrganizationIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/organization/$slug': {
      id: '/_public/organization/$slug'
      path: '/organization/$slug'
      fullPath: '/organization/$slug'
      preLoaderRoute: typeof PublicOrganizationSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/post/$slug': {
      id: '/_public/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PublicPostSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/friend-links/': {
      id: '/admin/friend-links/'
      path: '/friend-links'
      fullPath: '/admin/friend-links/'
      preLoaderRoute: typeof AdminFriendLinksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/muted-users/': {
      id: '/admin/muted-users/'
      path: '/muted-users'
      fullPath: '/admin/muted-users/'
      preLoaderRoute: typeof AdminMutedUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/api-keys': {
      id: '/admin/settings/api-keys'
      path: '/api-keys'
      fullPath: '/admin/settings/api-keys'
      preLoaderRoute: typeof AdminSettingsApiKeysRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/data-sources': {
      id: '/admin/settings/data-sources'
      path: '/data-sources'
      fullPath: '/admin/settings/data-sources'
      preLoaderRoute: typeof AdminSettingsDataSourcesRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/maintenance': {
      id: '/admin/settings/maintenance'
      path: '/maintenance'
      fullPath: '/admin/settings/maintenance'
      preLoaderRoute: typeof AdminSettingsMaintenanceRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/notifications': {
      id: '/admin/settings/notifications'
      path: '/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/site': {
      id: '/admin/settings/site'
      path: '/site'
      fullPath: '/admin/settings/site'
      preLoaderRoute: typeof AdminSettingsSiteRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/tags/': {
      id: '/admin/tags/'
      path: '/tags'
      fullPath: '/admin/tags/'
      preLoaderRoute: typeof AdminTagsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/admin/posts/edit/$id': {
      id: '/admin/posts/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/posts/edit/$id'
      preLoaderRoute: typeof AdminPostsEditIdRouteRouteImport
      parentRoute: typeof AdminPostsRouteRoute
    }
    '/admin/posts/edit/$id/': {
      id: '/admin/posts/edit/$id/'
      path: '/'
      fullPath: '/admin/posts/edit/$id/'
      preLoaderRoute: typeof AdminPostsEditIdIndexRouteImport
      parentRoute: typeof AdminPostsEditIdRouteRoute
    }
    '/admin/posts/edit/$id/history': {
      id: '/admin/posts/edit/$id/history'
      path: '/history'
      fullPath: '/admin/posts/edit/$id/history'
      preLoaderRoute: typeof AdminPostsEditIdHistoryRouteImport
      parentRoute: typeof AdminPostsEditIdRouteRoute
    }
    '/admin/posts/edit/$id/history_/$revisionId': {
      id: '/admin/posts/edit/$id/history_/$revisionId'
      path: '/history/$revisionId'
      fullPath: '/admin/posts/edit/$id/history/$revisionId'
      preLoaderRoute: typeof AdminPostsEditIdHistoryRevisionIdRouteImport
      parentRoute: typeof AdminPostsEditIdRouteRoute
    }
  }
}

interface PublicAuthRouteRouteChildren {
  PublicAuthForgotPasswordRoute: typeof PublicAuthForgotPasswordRoute
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
  PublicAuthResetLinkRoute: typeof PublicAuthResetLinkRoute
  PublicAuthVerifyEmailRoute: typeof PublicAuthVerifyEmailRoute
}

const PublicAuthRouteRouteChildren: PublicAuthRouteRouteChildren = {
  PublicAuthForgotPasswordRoute: PublicAuthForgotPasswordRoute,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
  PublicAuthResetLinkRoute: PublicAuthResetLinkRoute,
  PublicAuthVerifyEmailRoute: PublicAuthVerifyEmailRoute,
}

const PublicAuthRouteRouteWithChildren = PublicAuthRouteRoute._addFileChildren(
  PublicAuthRouteRouteChildren,
)

interface PublicUserRouteRouteChildren {
  PublicUserProfileRoute: typeof PublicUserProfileRoute
}

const PublicUserRouteRouteChildren: PublicUserRouteRouteChildren = {
  PublicUserProfileRoute: PublicUserProfileRoute,
}

const PublicUserRouteRouteWithChildren = PublicUserRouteRoute._addFileChildren(
  PublicUserRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthRouteRoute: typeof PublicAuthRouteRouteWithChildren
  PublicUserRouteRoute: typeof PublicUserRouteRouteWithChildren
  PublicSplatRoute: typeof PublicSplatRoute
  PublicAboutRoute: typeof PublicAboutRoute
  PublicEnginesRoute: typeof PublicEnginesRoute
  PublicNavigatorRoute: typeof PublicNavigatorRoute
  PublicPolicyRoute: typeof PublicPolicyRoute
  PublicPostsRoute: typeof PublicPostsRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicUndergroundRoute: typeof PublicUndergroundRoute
  PublicUnsubscribeRoute: typeof PublicUnsubscribeRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicOrganizationSlugRoute: typeof PublicOrganizationSlugRoute
  PublicPostSlugRoute: typeof PublicPostSlugRoute
  PublicOrganizationIndexRoute: typeof PublicOrganizationIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthRouteRoute: PublicAuthRouteRouteWithChildren,
  PublicUserRouteRoute: PublicUserRouteRouteWithChildren,
  PublicSplatRoute: PublicSplatRoute,
  PublicAboutRoute: PublicAboutRoute,
  PublicEnginesRoute: PublicEnginesRoute,
  PublicNavigatorRoute: PublicNavigatorRoute,
  PublicPolicyRoute: PublicPolicyRoute,
  PublicPostsRoute: PublicPostsRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicUndergroundRoute: PublicUndergroundRoute,
  PublicUnsubscribeRoute: PublicUnsubscribeRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicOrganizationSlugRoute: PublicOrganizationSlugRoute,
  PublicPostSlugRoute: PublicPostSlugRoute,
  PublicOrganizationIndexRoute: PublicOrganizationIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminPostsEditIdRouteRouteChildren {
  AdminPostsEditIdHistoryRoute: typeof AdminPostsEditIdHistoryRoute
  AdminPostsEditIdIndexRoute: typeof AdminPostsEditIdIndexRoute
  AdminPostsEditIdHistoryRevisionIdRoute: typeof AdminPostsEditIdHistoryRevisionIdRoute
}

const AdminPostsEditIdRouteRouteChildren: AdminPostsEditIdRouteRouteChildren = {
  AdminPostsEditIdHistoryRoute: AdminPostsEditIdHistoryRoute,
  AdminPostsEditIdIndexRoute: AdminPostsEditIdIndexRoute,
  AdminPostsEditIdHistoryRevisionIdRoute:
    AdminPostsEditIdHistoryRevisionIdRoute,
}

const AdminPostsEditIdRouteRouteWithChildren =
  AdminPostsEditIdRouteRoute._addFileChildren(
    AdminPostsEditIdRouteRouteChildren,
  )

interface AdminPostsRouteRouteChildren {
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminPostsEditIdRouteRoute: typeof AdminPostsEditIdRouteRouteWithChildren
}

const AdminPostsRouteRouteChildren: AdminPostsRouteRouteChildren = {
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminPostsEditIdRouteRoute: AdminPostsEditIdRouteRouteWithChildren,
}

const AdminPostsRouteRouteWithChildren = AdminPostsRouteRoute._addFileChildren(
  AdminPostsRouteRouteChildren,
)

interface AdminSettingsRouteRouteChildren {
  AdminSettingsApiKeysRoute: typeof AdminSettingsApiKeysRoute
  AdminSettingsDataSourcesRoute: typeof AdminSettingsDataSourcesRoute
  AdminSettingsMaintenanceRoute: typeof AdminSettingsMaintenanceRoute
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
  AdminSettingsSiteRoute: typeof AdminSettingsSiteRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsApiKeysRoute: AdminSettingsApiKeysRoute,
  AdminSettingsDataSourcesRoute: AdminSettingsDataSourcesRoute,
  AdminSettingsMaintenanceRoute: AdminSettingsMaintenanceRoute,
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
  AdminSettingsSiteRoute: AdminSettingsSiteRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminPostsRouteRoute: typeof AdminPostsRouteRouteWithChildren
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminSplatRoute: typeof AdminSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFriendLinksIndexRoute: typeof AdminFriendLinksIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminMutedUsersIndexRoute: typeof AdminMutedUsersIndexRoute
  AdminTagsIndexRoute: typeof AdminTagsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPostsRouteRoute: AdminPostsRouteRouteWithChildren,
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminSplatRoute: AdminSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFriendLinksIndexRoute: AdminFriendLinksIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminMutedUsersIndexRoute: AdminMutedUsersIndexRoute,
  AdminTagsIndexRoute: AdminTagsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApiAuthRouteChildren {
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

const ApiAuthRouteChildren: ApiAuthRouteChildren = {
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}

const ApiAuthRouteWithChildren =
  ApiAuthRoute._addFileChildren(ApiAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AtomDotxmlRoute: AtomDotxmlRoute,
  FeedDotjsonRoute: FeedDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SiteDotwebmanifestRoute: SiteDotwebmanifestRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsDotjsRoute: StatsDotjsRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthRoute: ApiAuthRouteWithChildren,
  ApiSendRoute: ApiSendRoute,
  ImagesSplatRoute: ImagesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
